name: Novillian Ops
title: Ops is Novillian
url: http://novillian.com
description: No something at least...

permalink: /:year/:title/
paginate: 10
highlighter: bourbon

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-coffeescript

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
